SELECT DISTINCT(CAR_ID),
       IF(MAX(END_DATE) >= '2022-10-16', '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-10-16'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

'''
<Mysql IF문>

IF(조건문, 참일 경우 값, 거짓일 경우 값)

'''